"""create initial schema

Revision ID: e1ed02751cfd
Revises: 
Create Date: 2026-07-13 21:41:19.201461

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1ed02751cfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icd10_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icd10_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_icd10_codes_code'))
    )
    op.create_index('ix_icd10_codes_category', 'icd10_codes', ['category'], unique=False)
    op.create_index('ix_icd10_codes_code', 'icd10_codes', ['code'], unique=False)
    op.create_index('ix_icd10_codes_search_text', 'icd10_codes', ['search_text'], unique=False)
    op.create_table('patients',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('normalized_first_name', sa.String(length=100), nullable=False),
    sa.Column('normalized_last_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index('ix_patients_normalized_name_dob', 'patients', ['normalized_last_name', 'normalized_first_name', 'date_of_birth'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PROVIDER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_entity_lookup', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('provider_profiles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_provider_profiles_user_id'))
    )
    op.create_table('templates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_templates_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_templates_name'))
    )
    op.create_index('ix_templates_deleted_at', 'templates', ['deleted_at'], unique=False)
    op.create_index('ix_templates_is_active', 'templates', ['is_active'], unique=False)
    op.create_table('encounters',
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', name='encounter_status'), nullable=False),
    sa.Column('encounter_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_encounters_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('fk_encounters_provider_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_encounters_template_id_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounters'))
    )
    op.create_index('ix_encounters_encounter_date', 'encounters', ['encounter_date'], unique=False)
    op.create_index('ix_encounters_patient_id', 'encounters', ['patient_id'], unique=False)
    op.create_index('ix_encounters_provider_date', 'encounters', ['provider_id', 'encounter_date'], unique=False)
    op.create_index('ix_encounters_provider_id', 'encounters', ['provider_id'], unique=False)
    op.create_index('ix_encounters_status', 'encounters', ['status'], unique=False)
    op.create_index('ix_encounters_template_id', 'encounters', ['template_id'], unique=False)
    op.create_table('template_sections',
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section', sa.Enum('GENERAL', 'SUBJECTIVE', 'OBJECTIVE', 'ASSESSMENT', 'PLAN', name='template_section_type'), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_template_sections_template_id_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_sections')),
    sa.UniqueConstraint('template_id', 'section', name='uq_template_sections_template_section')
    )
    op.create_index('ix_template_sections_template_id_sort_order', 'template_sections', ['template_id', 'sort_order'], unique=False)
    op.create_table('encounter_drafts',
    sa.Column('encounter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('selected_icd10_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_drafts_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_drafts')),
    sa.UniqueConstraint('encounter_id', name=op.f('uq_encounter_drafts_encounter_id'))
    )
    op.create_table('notes',
    sa.Column('encounter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_notes_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes')),
    sa.UniqueConstraint('encounter_id', name=op.f('uq_notes_encounter_id'))
    )
    op.create_table('note_versions',
    sa.Column('note_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('saved_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('icd10_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_versions_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_by_user_id'], ['users.id'], name=op.f('fk_note_versions_saved_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_versions')),
    sa.UniqueConstraint('note_id', 'version_number', name='uq_note_versions_note_version')
    )
    op.create_index('ix_note_versions_note_id_created_at', 'note_versions', ['note_id', 'created_at'], unique=False)
    op.create_foreign_key(
        'fk_notes_current_version_id_note_versions',
        'notes',
        'note_versions',
        ['current_version_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notes_current_version_id_note_versions', 'notes', type_='foreignkey')
    op.drop_index('ix_note_versions_note_id_created_at', table_name='note_versions')
    op.drop_table('note_versions')
    op.drop_table('notes')
    op.drop_table('encounter_drafts')
    op.drop_index('ix_template_sections_template_id_sort_order', table_name='template_sections')
    op.drop_table('template_sections')
    op.drop_index('ix_encounters_template_id', table_name='encounters')
    op.drop_index('ix_encounters_status', table_name='encounters')
    op.drop_index('ix_encounters_provider_id', table_name='encounters')
    op.drop_index('ix_encounters_provider_date', table_name='encounters')
    op.drop_index('ix_encounters_patient_id', table_name='encounters')
    op.drop_index('ix_encounters_encounter_date', table_name='encounters')
    op.drop_table('encounters')
    op.drop_index('ix_templates_is_active', table_name='templates')
    op.drop_index('ix_templates_deleted_at', table_name='templates')
    op.drop_table('templates')
    op.drop_table('provider_profiles')
    op.drop_index('ix_audit_logs_entity_lookup', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_patients_normalized_name_dob', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_icd10_codes_code', table_name='icd10_codes')
    op.drop_index('ix_icd10_codes_category', table_name='icd10_codes')
    op.drop_index('ix_icd10_codes_search_text', table_name='icd10_codes')
    op.drop_table('icd10_codes')
    # ### end Alembic commands ###
